version: "3.8"
services:
  redis:
    image: redis:7
    command: ["sh", "/usr/local/bin/entrypoint.sh"]
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
      - ./redis.conf:/usr/local/etc/redis/redis.conf
      - ./entrypoint.sh:/usr/local/bin/entrypoint.sh
    deploy:
      replicas: 3
      placement:
        preferences:
          - spread: node.hostname
      restart_policy:
        condition: on-failure
    networks:
      - redis-net

volumes:
  redis-data:

networks:
  redis-net:
    driver: overlay

